/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lib;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sayed Mahmud Raihan
 */
public class log extends javax.swing.JFrame {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
    public log() {
        initComponents();
        conn = DatabaseConnect.rw();
        setLocationRelativeTo(null);
        Update_table();
    }
    public void close(){
         WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    private void Update_table(){
        try{
                SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
                Date da = new Date();
                
                String nl = null;
//                String sql = "select * from log where book_exp_date < '"+sf.format(da)+"'";
                
                String sql = "select * from log where return_date is null and book_exp_date < '" +sf.format(da) +"'";
                
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                log_table.setModel(DbUtils.resultSetToTableModel(rs));
                
//                while(rs.next())
//                {
//                    System.out.println("--> "+rs.getString("return_date"));
//                }
            
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        log_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        log_mem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nam = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        ses = new javax.swing.JTextField();
        dptm = new javax.swing.JTextField();
        mo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        log_table.setAutoCreateRowSorter(true);
        log_table.setBackground(new java.awt.Color(204, 204, 255));
        log_table.setBorder(new javax.swing.border.MatteBorder(null));
        log_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        log_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Log_id", "Member ID", "Call No", "Accession", "Borrow Date", "Exp Date", "Return Date", "Fine"
            }
        ));
        log_table.setToolTipText("");
        log_table.setInheritsPopupMenu(true);
        log_table.setName(""); // NOI18N
        log_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(log_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 50, 478, 400));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 52, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Roll No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 83, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Session");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 83, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Department");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 62, 32));

        log_mem.setEditable(false);
        log_mem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(log_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 54, 102, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 52, 76, 30));

        nam.setEditable(false);
        nam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, 183, 30));

        roll.setEditable(false);
        roll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 195, 183, 30));

        ses.setEditable(false);
        ses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ses, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 266, 183, 30));

        dptm.setEditable(false);
        dptm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(dptm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 183, 30));

        mo.setEditable(false);
        mo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 183, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Book Return Date Expired List");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_tableMouseClicked
        try {
                int row = log_table.getSelectedRow();
                String Table = (log_table.getModel().getValueAt(row, 0).toString());
                String sql = "select * from log where log_id='" + Table + "' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    String add1 = rs.getString("member_id");
                    log_mem.setText(add1);
                    
                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
    }//GEN-LAST:event_log_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        main_form mf = new main_form();
        mf.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String memberid = log_mem.getText();
            String sql = "select name,roll_no,session,department,contact_no from student where member_id='"+memberid+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String names = rs.getString("name");
                nam.setText(names);
                String rol = rs.getString("roll_no");
                roll.setText(rol);
                String seession = rs.getString("session");
                ses.setText(seession);
                String dpt = rs.getString("department");
                dptm.setText(dpt);
                String mb = rs.getString("contact_no");
                mo.setText(mb);
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void log_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_tableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_log_tableMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dptm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField log_mem;
    private javax.swing.JTable log_table;
    private javax.swing.JTextField mo;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField ses;
    // End of variables declaration//GEN-END:variables
}
